# Generated by Django 2.2.2 on 2019-07-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('enfermedad_padecida', models.CharField(max_length=200, verbose_name='Enfermedad padecida')),
                ('enfermedad_hereditarias', models.TextField(blank=True, verbose_name='Enfermedades hereditarias')),
            ],
            options={
                'ordering': ['codigo', 'enfermedad_padecida', 'enfermedad_hereditarias'],
            },
        ),
    ]
